// The only doorway between the page and the rest of the PC.
const { contextBridge, ipcRenderer, webUtils } = require('electron');

const call = (channel) => (...args) => ipcRenderer.invoke(channel, ...args);

// The page's own script errors go to Notebook's error log (main/errlog.js).
window.addEventListener('error', (e) => ipcRenderer.send('log:error', `${e.message} (${e.filename}:${e.lineno}:${e.colno})`));
window.addEventListener('unhandledrejection', (e) => ipcRenderer.send('log:error', 'unhandled: ' + (e.reason && (e.reason.stack || e.reason.message) || String(e.reason))));

contextBridge.exposeInMainWorld('nb', {
  onTrayMenu: fn => ipcRenderer.on('ui:tray', () => fn()),
  quit: call('app:quit'),
  onUIRequest: fn => ipcRenderer.on('ui:request', (_e, request) => fn(request)),
  replyUI: call('ui:reply'),
  browseFiles: call('ui:browse'),
  filePlaces: call('ui:places'),
  createFolder: call('ui:mkdir'),
  state: call('lib:state'),
  useLibrary: call('lib:use'),
  revealLibrary: call('lib:reveal'),
  revealItem: call('item:reveal'),
  pickFiles: call('items:pick'),
  importPaths: call('items:import'),
  importData: call('items:importData'),
  reorderBoards: call('boards:reorder'),
  updateItem: call('item:update'),
  saveThumb: call('item:thumb'),
  rawThumb: call('item:rawThumb'),
  moveToBin: call('item:bin'),
  setOnPhone: call('items:onPhone'),
  stackItems: call('items:stack'),
  unstackItem: call('item:unstack'),
  restore: call('item:restore'),
  addNote: call('note:add'),
  emptyBin: call('bin:empty'),
  addBoard: call('board:add'),
  renameBoard: call('board:rename'),
  setBoardOnPhone: call('board:onPhone'),
  deleteBoard: call('board:delete'),
  backup: call('backup:run'),
  autoBackup: call('backup:auto:get'),
  setAutoBackup: call('backup:auto:set'),
  autoBackupFolder: call('backup:auto:folder'),
  onAutoBackup: (fn) => ipcRenderer.on('backup:auto', (_e, s) => fn(s)),
  restoreBackup: call('backup:restore'),
  exportAll: call('export:run'),
  pathForFile: (file) => webUtils.getPathForFile(file),
  // Recognition, styles and suggestions (build plan Track A)
  aiStatus: call('ai:status'),
  setLabels: call('ai:labels'),
  setStyles: call('ai:setStyles'),
  rescan: call('ai:rescan'),
  suggestions: call('suggest:list'),
  dismissSuggestion: call('suggest:dismiss'),
  renameSuggestion: call('suggest:rename'),
  keepSuggestion: call('suggest:keep'),
  onAiProgress: (fn) => ipcRenderer.on('ai:progress', (_e, s) => fn(s)),
  // Saving from links and the Pinterest panel (build plan Track B)
  saveLink: call('links:save'),
  links: call('links:list'),
  forgetLink: call('links:forget'),
  checkLinks: call('links:check'),
  updateDownloader: call('links:update'),
  onLinkSaving: (fn) => ipcRenderer.on('links:saving', (_e, s) => fn(s)),
  onLinkSaved: (fn) => ipcRenderer.on('links:saved', (_e, s) => fn(s)),
  pinOpen: call('pin:open'),
  pinBounds: call('pin:bounds'),
  pinClose: call('pin:close'),
  pinBack: call('pin:back'),
  pinHome: call('pin:home'),
  pinSave: call('pin:save'),
  pinAiSetting: call('pin:aiSetting'),
  onPinAi: (fn) => ipcRenderer.on('pin:ai', (_e, s) => fn(s)),
  pinGo: call('pin:go'),
  onPinState: (fn) => ipcRenderer.on('pin:state', (_e, s) => fn(s)),
  // Ideas (the Pinterest-style feed)
  searchPictures: call('search:pictures'),
  feed: call('feed:get'),
  feedRefresh: call('feed:refresh'),
  feedMore: call('feed:more'),
  feedHide: call('feed:hide'),
  feedSave: call('feed:save'),
  onFeedChanged: (fn) => ipcRenderer.on('feed:changed', (_e, s) => fn(s)),
  // Phone sync
  syncOpen: call('sync:open'),
  syncStatus: call('sync:status'),
  syncNewCode: call('sync:newCode'),
  syncUnpair: call('sync:unpair'),
  syncKeepReady: call('sync:keepReady'),
  onLibraryChanged: (fn) => ipcRenderer.on('lib:changed', (_e, payload) => fn(payload)),
  onSyncChanged: (fn) => ipcRenderer.on('sync:changed', () => fn())
});
